#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the first argument:
#           sh -c "SHELL=/bin/bash ./gradlew ..."
#       or you could set SHELL and run it:
#           SHELL=/bin/bash ./gradlew ...
#
#   (2) This script attempts to detect the Java installation directory
#       and set JAVA_HOME accordingly. If it cannot, it will fall back to
#       using the 'java' command. You can set JAVA_HOME explicitly by
#       setting the environment variable.
#
#   (3) This script will set the GRADLE_USER_HOME directory to the
#       user's home directory if it isn't set. You can set GRADLE_USER_HOME
#       explicitly in the environment.
#
#   (4) This script uses the 'uname' command to detect the OS and determine
#       the architecture of the JVM. It also uses the 'cut' command to
#       parse the output of 'uname'. If these commands are not available,
#       the script will attempt to fall back to using the 'arch' command.
#
#   (5) You can run this script with the '--dry-run' option to see what
#       would happen without executing anything.
#
#   (6) If the JVM is not found, the script will try to find the Java
#       Runtime Environment (JRE) as a fallback.
#
#   (7) This script uses the 'java' command. If it's not available,
#       it will try to find the Java Runtime Environment (JRE) in the
#       same way.
#
#   (8) This script is POSIX-compliant and does not use any Bash-specific
#       features.
#
#   (9) This script will remove the TMPDIR directory after the script
#       execution if it created it.
#
##############################################################################

#   Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi

# Collect the arguments - many were defined earlier
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args.
# The use of "xargs" is required because the shell loses quote escaping
# when using the `set --` varargs syntax, and the `while` loop cannot
# consume them because it uses the `shift` builtin and the `$@` automatic
# parameter. The `xargs` command will parse and preserve the quotes.
# Use of "xargs" is also required to handle the line wrapping that the
# `while` builtin cannot do.
# The use of "xargs" also has the side effect that the args are all
# converted to a single line, which is then split by the IFS.
# The IFS is set to space by default in POSIX, which also handles tabs
# and newlines.
#
# We cannot use the `xargs -0` because it requires the `-0` option,
# which is not a POSIX option.

# Escape application args
save_ifs=$IFS; IFS=
for arg in "$@"; do
    set -- "$@" "$arg"
done
IFS=$save_ifs

# Collect the arguments
set -- $(
    xargs <<-END
        "$@"
END
)

# Add the DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS
eval set -- "$DEFAULT_JVM_OPTS" '"$@"' "$JAVA_OPTS" "$GRADLE_OPTS"

# Run the main class
exec "$JAVACMD" "$@"